### ISSUE TITLE
Bug: Fullscreen PicoTorrent restores down when opening torrents from outside

### ISSUE THREAD

**Issue by michalsieron** [picotorrent/picotorrent#1030]
Didn't really know how to decribe it in title.

When I want to open .torrent file or magnet link with PicoTorrent it restores down to not-maximized window. It happens only when PicoTorrent is already opened.

IIRC it happened before, but there was period when it didn't occur. I don't really know what graphics library PicoTorrent is currently built upon ("About" and documentation state that it's still wxWidgets, while home page says it's Windows API), but I think that wxWidgets (or maybe it was Qt?) didn't have this problem.

Steps:
  1. Open PicoTorrent
  2. Maximize the window
  3. Open some .torrent file or magnet link with PicoTorrent
  4. PicoTorrent window restores down from being maximized

**Comment by vktr** [comment]
Hey @michalsieron! Thanks for the report - I can confirm the behavior. Re: graphics library - we use wxWidgets now, which we have used before, with Qt in between. We used the pure Windows API's for the first few versions 😄 The home page is outdated re: that information, but technically correct since wxWidgets builds on Windows API's which Qt does not.
