### ISSUE TITLE
suggestion: Using NSIS as installer engine

### ISSUE THREAD

**Issue by AHOHNMYC** [picotorrent/picotorrent#1142]
It seems strange to create own installer in world where NSIS exists. Here is why:
- current installer uses .NET as dependency, while main application does not require it
- .NET causes slow loading
- NSIS out of box has integrated i10n on 67 languages and key for silent setup
- NSIS uses more effective compression algorithm LZMA, instead of current LZX in CAB (4.1 MB vs 5 MB)
- NSIS does not require massive programming, just one nsi file

So, I suggest [NSIS](//nsis.sourceforge.io) instead of current one.

**Comment by vktr** [comment]
Hello @AHOHNMYC!

> current installer uses .NET as dependency, while main application does not require it

While true, it does not depend on any recent version of .NET and 9 out of 10 times the required .NET version (4.5) would already be installed.

> .NET causes slow loading

Do you have numbers to support this case?

> NSIS out of box has integrated i10n on 67 languages and key for silent setup

I doubt NSIS has translations for our strings. MSI also has silent setup.

> NSIS uses more effective compression algorithm LZMA, instead of current LZX in CAB (4.1 MB vs 5 MB)

Reducing installer size would be nice, but I like what WiX gives us and I think the trade-off is worth it.

> NSIS does not require massive programming, just one nsi file

Neither does MSI/WiX. I chose to build a custom bootstrapper since I wanted some features not supported by the standard one.

There are many reasons I chose MSI/WiX for building the installer. Including,

- Being the *de facto* standard way of [installing software on Windows](https://docs.microsoft.com/en-us/windows/win32/msi/windows-installer-portal).
- Transactional installation with support for rollbacks in case of errors.
- No real programming required - you describe the desired state and the installer will take care to match that. The source for our bootstrapper is just a UI layer on top of the actual MSI file.

I've used NSIS with success in other projects, and while it is easy to use, MSI provides a far greater feature-set.

**Comment by AHOHNMYC** [comment]
Thanks for the detailed answer. I missed the forest for the trees and MSI hidden in EXE. Got your idea with WiX and bootstrapper.
So, now I only may offer help with translation of this bootstrapper (there are two issues with same suggestion).
And to ask you to point silent install and other (if they are exists) keys in `readme`. Because now neither of most common help keys (`/? -? /h -h --h -help --help`) return any help messagebox.
Thank you in advance.

**Comment by vktr** [comment]
Passing `/quiet` should enable silent mode. I'll make sure to add it to the docs 😄
