### ISSUE TITLE
Add torrent dialog crash when setting file priority

### ISSUE THREAD

**Issue by zp** [picotorrent/picotorrent#120]
When you set the priority of the last file in a torrent to 'Do not download' in the 'Add torrent' dialog, picotorrent crashes when you attempt add it.

````
INFO - 23:03:25.961 - picotorrent::core::session::load - Loading session
INFO - 23:03:26.82 - picotorrent::core::session::load_state - Session state loaded
INFO - 23:03:26.82 - picotorrent::core::session::load_torrents - Loading 0 torrent(s)
FATAL - 23:03:32.410 - picotorrent::logging::log::on_unhandled_exception - Unhandled exception occured
at "RaiseException" 
at "CxxThrowException" 
at "std::_Xout_of_range" 
at "std::map<libtorrent::sha1_hash,std::shared_ptr<picotorrent::core::torrent>,std::less<libtorrent::sha1_hash>,std::allocator<std::pair<libtorrent::sha1_hash const ,std::shared_ptr<picotorrent::core::torrent> > > >::at" (line 359)
at "picotorrent::core::session::notify" (line 422)
at "picotorrent::common::signals::signal<void,void>::emit" (line 106)
at "picotorrent::ui::main_window::wnd_proc" (line 203)
at "picotorrent::ui::main_window::wnd_proc_proxy" (line 540)
at "DispatchMessageW" 
at "DispatchMessageW" 
at "picotorrent::app::message_loop::run" (line 12)
````

Also, if you set the last file's priority to 'High' or 'Maximum', when you add the torrent all of the other files get set to 'Do not download' (strangely it doesn't crash)

edit: crashes with single file torrents as well when you set the priority to 'Do not download'

**Comment by vktr** [comment]
Thanks! I can reproduce both issues.

When adding a multi-file torrent and changing the last file priority, I resize the file priority array. I did not specify a new default value for the elements which were added, so it defaulted to `0` (do not download). That is one issue, which is an easy fix.

If you set the last (or only) file in a torrent to *Do not download*, the file priority array will contain all zeros (since it defaulted to zero when resizing). When libtorrent receives this, it notices that no files are to be downloaded, and we receive a `torrent_finished_alert` *before* receiving the `add_torrent_alert`.

I don't know if this is to be expected, but I've asked and am waiting for input here, https://github.com/arvidn/libtorrent/issues/458.

Either way, I need to fix it :smile:
