### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by ClementNerma** [picotorrent/picotorrent#1239]
Hi there!

I've been using PicoTorrent on a daily basis for quite a bit of time now and I'm really enjoying it - it's simple, fast and clean.

But I recently wondered why I didn't get update for a long time, and checking the repository there last commit is from 8 Aug 2021! Which is 9 months.

So, is the project still active? There are 161 opened issues as of today (not counting this one) so I'm curious to know if there is still any active development going on here.

**Comment by vktr** [comment]
Hi!

Yeah, there's been a year since the last release. I haven't really had energy to spend which is why development has stopped for a while. I don't think there's any critital open issues so I have just let things be the way they are.

So the project might have been inactive the last year, but it is not abandoned. I have a few major things I want to fix before doing a v1.0 release, I just haven't had time 😄

**Comment by ClementNerma** [comment]
No problem, thanks for your answer!
