### ISSUE TITLE
Ability to change "Close to Tray" option.

### ISSUE THREAD

**Issue by adamspruijt** [picotorrent/picotorrent#287]
If you choose not to close the program to the tray and check "don't ask me again", there it then no way to go back on this choice in the settings. Also, an uninstall and reinstall does not clear this setting.

**Comment by vktr** [comment]
You can manually edit the `PicoTorrent.json` configuration file and remove the `close_action` property if you want to reset the setting.

The file is located at `%APPDATA%/PicoTorrent/PicoTorrent.json` if PicoTorrent is installed.

**Comment by svnpenn** [comment]
@vktr I would like to piggyback on this issue. Here are the current window
options:

- Minimize
- Close

Or:

- Minimize
- Send to tray

This confuses me because I feel like if you want to send to tray, you probably
DONT want to minimize. So it would make sense to ditch the minimize option
rather than the close option. If you choose the second option and you want to
close the program the only option is through the tray. I feel the "X" should
always be for terminating the program. Here is my suggestion:

- Send to tray
- Close

So if you click Minimize it will send to tray, and if you click close it will
terminate the program.

**Comment by vktr** [comment]
@svnpenn The current dialog looks like this,

![image](https://cloud.githubusercontent.com/assets/1491824/15531482/daf5d720-225a-11e6-98e6-8a2ed30348c2.png)

I fail to see the confusion this would cause. It works similar to closing Notepad with unsaved changes, but instead it asks you if you really want to *exit* or just want PicoTorrent to *get out of the way*. There are lots of examples of applications doing this (or something similar).

To terminate the program without any prompt at all, use the `File -> Exit` menu item.

**Comment by svnpenn** [comment]
@vktr perhaps this will clear it up:

> ![qbittorrent][1]

This is a screenshot from Qbittorrent options. As can be seen, user has full
control over the tray, you can:

- [x] disable tray use completely
- [x] minimize to tray
- [x] close to tray
- [x] minimize and close to tray

compare this to PicoTorrent capabilities:

- [ ] disable tray use completely
- [ ] minimize to tray
- [x] close to tray
- [ ] minimize and close to tray

[1]:
//cloud.githubusercontent.com/assets/926619/15540749/b999be54-224e-11e6-8e04-41e9313ef585.png

**Comment by adamspruijt** [comment]
thanks for the help @vktr I will edit my JSOn config. Does seems as @svnpenn is pointing out that long term the configuration options he mentioned could solve his issue and my own.

Seems this is solved for the time.
