### ISSUE TITLE
Ability to attach details

### ISSUE THREAD

**Issue by Skulld** [picotorrent/picotorrent#313]
(I understand that not everyone likes another tab in 1-tab program, so i speak mostly about ability)
it would very comfortable to attach 'details'->'files' on the bottom of app, like in other torrent app - to change priority and see progress of every file without additional clicking.
Especially, with ability to tray\expand.

**Comment by mutt3x** [comment]
Im not sure what you mean when you say ability; you mean like an On/Off option or something?
If people wont use it there is no point of having it.
In this case people are used to the (bloat) design of other clients so...
If you mean its implemented for all i just think any tab-like design will break the pure minimalist design for the price of what... two clicks.

>change priority and see progress of every file without additional clicking

hmm
Perhaps adding a **Details Hotkey** is much more acceptable then adding tab attachments. Keeps the minimalist look and with one clicks less its spawns the details. Maybe even add a partner Files Hotkey... thats also a possibility for you.
EVEN BETTER
By adding a small icon/button in the line of the torrent that directly opens said stuff. It could be an on/off column (as all columns should be). It doesen't even need to be an icon it could be: F files, D details... That simple.
**Exsample:**
Torrent name | # | D F P T | size | status | IIIIIII-----% | ETA | ...
-DFPT are clickable buttons.
Seems the program space is used more efficiently this way (compared to tabs) and you get less clicks as well.

>like in other torrent app

Every client today is a (obvious) ripoff of the other one avaiable in one way or another (except transmission). Its always better to be unique rather than a copy. If something is going to be replicated, please let it be torrenting options/features.

I have no life. :3

**Comment by vktr** [comment]
For now, I think we will stick with what we have (a details dialog) instead of a details tab view at the bottom.

A tip though, you can bring up the details dialog by double clicking a torrent (or pressing `Enter` with a torrent selected).
