### ISSUE TITLE
Possibility to add any language file in the picotorrent folder

### ISSUE THREAD

**Issue by TechnoGreg** [picotorrent/picotorrent#497]
Since the last version, the languages are embedded in the executable file.
I suggest that we can add any language file (*.json) in the same folder that the exe file to add it in the program.

**Comment by vktr** [comment]
Hi @TechnoGreg! I moved the JSON files to embedded in the executable to keep the release process easy, since I sometimes forgot to add a language to the installer, for example. I'll definitely add the option to side-load language files from a specific folder as well, though. Thanks for your patience!
