### ISSUE TITLE
multiple feature requests

### ISSUE THREAD

**Issue by jlkkljh** [picotorrent/picotorrent#501]
feature requests
double click on statusbar areas to open relevant areas (example) speed opens the global limits dialogue 
ability to use custom tracker list (possibly via trackers.txt in app folder)
keep executable up a directory from everything else
default downloads to an in-folder location (downloads-completed/downloads-uncompleted)
ability to add user extensions
ability to crc/sha, easily done
option to auto extract (preferable via checkbox) stored in %name%-extracted
7zip/winrar integration? 7zip is open source and supports 90% of archives, idk about winrar (sorry lol)
chat function via irc/iirc? could use a public irc (look for one that doesn't collect logs) 
comments from fellow peers
category filters (music/movie/game/archive)
internal search (could be in top right on menu bar)
option to prefer encryption, if available
option to use DHT or not
option to use peer exchange or not
upnp/nat-pmp
port options (random, random new each startup, specify, blank for default)
confirm on exit
virus total integration/checking
option for notification for completed downloads
option to report bugs
option to "share" torrent
option to download torrent only
edit:more
higher priority downloads get more bandwidth via variable speed allocation that divides available bw between # of downloads running, following download limits (lets say max down is 100kbps give first prio maybe 50kb, second prio 25kb, third gets 12.5kb. if only two give top 75kb, second 25kb. if only one then 100kb.

could use portableapps framework to make sure it stays portable

i am loving this so far, thank you. sorry if i request something that is already implemented
maybe some easter eggs? but thats me being silly

**Comment by ArtexJay** [comment]
Why do you want an archiver integration? (I'd personally look at Peazip, supports way more archives than winrar or 7z)
What kind of extension is there to add to a torrent client?
And why would we need the chat function?
Or integration of Virus total?

Im just curious, since i either do not find them useful or i dont know much about them.

**Comment by jamesaepp** [comment]
I would say stick to the unix philosophy if we can, especially if the package is meant to be as tiny as possible, which I assume is kind of the point. I would have also recommended to make separate feature requests/tickets as opposed to one big post. Makes it harder to have effective discourse, as we'll soon discover.

Keep executable up a directory.
Please clarify. You refer to %ProgramFiles%\PicoTorrent ? You want the exe in (what I'll call) . and say, the dlls in .\lib ? 

CRC/SHA -- For what purpose? The BT protocol, and I assume libtorrent/rasterbar has the checksum nature built-in. I don't know if it hashes after each file is downloaded, but I'd assume so. Also, doing CRC/SHA checksums is all fine and dandy, but what are you using to compare the hash to? Not all torrents include a .sha1sum file, and this function is not built-in to the protocol. I fail to see the rational for this.

Comments from fellow peers -- this is what tracker websites are for. This is not the job of the client to maintain.

Option to report bugs -- Do you mean in regards to if the program crashes or experiences a runtime error? 

Option to share torrent -- for what purpose? If I share torrents between friends I copy the info hash or magnet link and send to whoever. Picotorrent already has this

Option to download torrent only -- Please clarify. Do you mean to only take the magnet link or info hash and download the .torrent file from the DHT/PEX and save it to local storage? Or do you mean to enable leaching? I am pro former, opposed to the latter. I don't believe any torrent client should make leaching easy. It's bad for all netizens.

User extensions / Auto Extraction / Chat integration / labels or filters / virus total queries -- You already said way above the ability to add user extensions. I'm biased into the unix philosophy. I'm okay with a variable for each torrent for "when complete execute ....." to call a script or do a single powershell or CMD line with certain variables made available. I don't think any of this is worth shipping from this package. Keep the package as small as possible. 

I came to notice picotorrents existence because I needed to make a 600MB transfer over the slowest link. Even picotorrent took a full minute to download. Do you think I want to download an even bigger package with features I won't use? No. If I want a full torrent client experience like you mention, here's what I would do. It's silly, but it's sort of what we've been doing since Mozilla Firefox and Google Chrome became mainstream. The first two steps should be familiar to my point. :)

1. Open IE to picotorrent.org website and download the package (think chrome/firefox)
2. Post-download, install picotorrent
3. Decide I want qbittorrent or deluge or whatever, but a 30MB package might be too much for my link to accommodate over traditional HTTP traffic
4. Use whatever means I have available to me (lightweight IRC, or a phone conversation with a friend, or whatever else) to achieve a magnet link for the "heavier/more feature rich" torrent client of my choice
5. Download the new torrent client using picotorrent
6. Continue with my workflow from here, with whatever features the other client has that I require

There's no point in making a small client into a monolithic one when the monolithic clients already exist, are GPL licensed, and have high popularity. If picotorrent is a "gateway client" to other more feature-rich clients -- hey! There's nothing wrong with that.

**Comment by mutt3x** [comment]
>chat function via irc/iirc? could use a public irc (look for one that doesn't collect logs)
Where is the weed that you are smoking because i want some. If logs were the only issue here...
IRC collects logs = bad
IRC does not collect logs = Hell yeah, now i can finally speak to my local fbi agent and share my torrents with him.

Yeah ugh, vktr can you also put a music and video player along with radio. Maybe make a game inside the torrent client... dont forget to make a facebook like button... actually no just make a new OS. ;) Go!!

**Comment by vktr** [comment]
I'm closing this due to a quite widespread request. If you feel strongly for one or more items in the request list, feel free to open issues per item, with details, so we have something we can discuss.
