### ISSUE TITLE
100% CPU when (re)connecting with Windscribe VPN

### ISSUE THREAD

**Issue by ltGuillaume** [picotorrent/picotorrent#567]
1. Start PicoTorrent
2. Connect using Windscribe VPN via the Windows application (you can try it for free)
3. As soon as the connection is established, PicoTorrent starts using 100% CPU (for one thread).

If Windscribe is already running when PicoTorrent is started, everything's fine, but a disconnection/reconnection results in the same thing.

OS: Windows 10 x64 1709

**Comment by ltGuillaume** [comment]
Alright, I just read [url=https://www.reddit.com/r/Windscribe/comments/8edz8d/qbittorrentpicotorrent_100_cpu_when_reconnecting/](on Reddit) that an issue for qBittorrent has opened since the creation of this issue, https://github.com/qbittorrent/qBittorrent/issues/8740.

The erratic behavior is caused by Windscribe terminating the socket by force in order to prevent any leaking while not connected to the VPN server.

This could either be addressed in the @libtorrent library, as hinted by 2 users in the issue, or a workaround could be implemented in the client (checking for existence of socket and aborting the endless connection retries which cause the CPU use).

**Comment by yegors** [comment]
Windscribe dev here. You can also reproduce the issue by terminating the TCP socket with https://www.nirsoft.net/utils/cports.html to take the VPN out of the equation. 

This issue seems to affect a wide range of software that doesn't handle unexpected socket termination. This includes Plex, qBittorrent, Acronis True Image, Avid Media Manager.

**Comment by yegors** [comment]
Still no fix here. :(
