### ISSUE TITLE
NullReferenceException AB

### ISSUE THREAD

**Issue by Eldaw** [picotorrent/picotorrent#605]
The name of the signer in the Digital Signature of the executable for v0.15.0 is 'NullReferenceException AB'.

**Comment by vktr** [comment]
Correct, and it has been that way since way back, if not even v0.1 :)
That is the name of my company to which the code signing certificate
is issued.
The common name for code signing certificates must be the legal name of
the company, so unfortunately we cannot have it say PicoTorrent or such.

On Fri, Apr 27, 2018, at 14:09, Eldaw wrote:
> The name of the signer in the Digital Signature of the executable for
> v0.15.0 is 'NullReferenceException AB'.> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[1], or mute the
> thread[2].> 


Links:

  1. https://github.com/picotorrent/picotorrent/issues/605

**Comment by Eldaw** [comment]
OK, it is an unfortunate name for the company. In the security software I'm using, it appeared to be a bug. I'd logged a bug ticket here, thinking it was a bug:
https://forum.glasswire.com/t/version-none-publisher-nullreferenceexception/6432

**Comment by Eldaw** [comment]
Signed builds are preferable. All I'm saying is that the choice of name is unfortunate, because when the name is flagged in security software it looks like a bug.
