### ISSUE TITLE
Some translation errors in last release

### ISSUE THREAD

**Issue by ryahpalma** [picotorrent/picotorrent#706]
@vktr The last release of Pico 0.15 have some translation issues, I compiled the last code and it seems that the issues have been resolved, could make this fix available to the official page, making installers available to the community. A great example is the bottom bar showing only the function instead of the translation: i64d_torrents.

**Comment by vktr** [comment]
Hi! Yeah, there's been a huge gap since the last release - I've been busy with life, work and other things. The good news is that a new release *is* coming - there's some exciting news regarding that as well.

One thing which have held back a release is that my code signing certificates have expired and they're hella expensive. I've been reluctant to make an unsigned release, but I think it's for the best if we roll forward without signing and then put signing in place again in the future.
