### ISSUE TITLE
Picotorrent: Can't select which files to download, I have to install the entire torrent.

### ISSUE THREAD

**Issue by Tall-Lobster** [picotorrent/picotorrent#763]
Dear Picotorrent Developer,

It would be great if you can add this feature as it would help with not downloading large torrents such as ones like the 56 GB ones and instead just downloading the 2 1MB files from a torrent file for example.

Thanks,

**Comment by Rakleed** [comment]
@Tall-Lobster when you open a .torrent file or magnet link in the “Add torrent (s)” window, you can cancel the download of some files if you do not need them. To do this, right-click on the file or folder, select Priority, then Do not download.

When the download has already begun, you can also choose which files to download and which not. To do this, you need to select the desired torrent, click Files on the bottom panel, then right-click on the desired file, select Priority and select Do not download if you do not need to download this file.

**Comment by VideoPlayerCode** [comment]
Maybe this should be moved to a separate right click menu item. Right now it is opening a menu with a single item named Priority. That submenu contains low/normal/max/do not download.

How about having "do not download" as a separate checkmark menu item outside of the Priority menu? 

Although I do see the benefits of the current system since it allows the Priority column to display "do not download" state.

**Comment by vktr** [comment]
It might make sense to move *do not download* to a checkbox in the item list. I'll have a look at this.

**Comment by vktr** [comment]
There is a checkbox in the file tree view now - closing this.
