### ISSUE TITLE
Error due to which it is not possible to install version 0.18

### ISSUE THREAD

**Issue by Rakleed** [picotorrent/picotorrent#794]
When I try to install the [latest version 0.18](https://github.com/picotorrent/picotorrent/releases/tag/v0.18.0), I get the error "The feature you are trying to use is on a network resource that is unavailable." I uninstalled the previous version, rebooted the computer and restarted the installer, but that did not help. I also tried to connect via VPN, but that didn't help either. What to do?

![image](https://user-images.githubusercontent.com/19418601/71678877-42aa7380-2d97-11ea-9894-1edd6e3b5938.png)

Logs:
[PicoTorrent_20200102194257_000_PicoTorrentPackage.log](https://github.com/picotorrent/picotorrent/files/4016578/PicoTorrent_20200102194257_000_PicoTorrentPackage.log)
[PicoTorrent_20200102194257.log](https://github.com/picotorrent/picotorrent/files/4016580/PicoTorrent_20200102194257.log)

**Comment by vktr** [comment]
Thanks for the report. I'll have a look.

**Comment by thec0mpler** [comment]
I am not familiar with how installing/upgrading works, but I maybe found some helpful information.

In the logs there are mentions of PicoTorrent version 0.17.0. Because the installer is probably trying to find related products, see lines 132 to 137 in 'PicoTorrent_20200102194257_000_PicoTorrentPackage.log'.

It looks like it is trying to find it at 'C:\ProgramData\Package Cache\{1C89BF65-2746-4057-8545-CD2B6D81F164}v0.17.0\PicoTorrent-0.17.0-x64.msi'. But I guess that locations does not exist (anymore).

Maybe installing version 0.17.0 and trying to upgrade again helps?

**Comment by vktr** [comment]
I think in this case the VC redist was not found (either because of an error at Microsoft’s urls or there was no internet connection) and that’s why it prompts for a package location instead as a last effort. 

I’m moving the VC redist packages to my own servers so they should be more available against this kind of stuff.

**Comment by Rakleed** [comment]
@vktr @thec0mpler

This is strange, but I was able to install version 0.18 using the .exe file.

How I could do it. I uninstalled PicoTorrent. Since I could not install version 0.18 using the .exe file, I downloaded and unpacked the zip archive. Now I decided to try to download the installer version 0.17, but at startup I was offered either to repair the application or delete it. I chose Repair, everything went well, but version 0.18 started, which was apparently unpacked from the archive. Next, I again launched the installer version 0.17 and uninstalled PicoTorrent. After that, I downloaded the installer version 0.18, launched it and the installation was successful.

**Comment by Rakleed** [comment]
I got a similar error that appears when installing and running other applications. Probably due to the fact that I used the utility to completely remove AdGuard, which broke something in the registry. After reinstalling Windows, this problem no longer exists.

**Comment by vktr** [comment]
Hey @Rakleed thanks for the follow-up! I've been busy with the rewrite for 0.19 and have been meaning to take a look at this at some point before that release, but I'm happy you got it working. Feel free to re-open if the issue comes back.
