### ISSUE TITLE
v0.15 is more stable

### ISSUE THREAD

**Issue by kaecy** [picotorrent/picotorrent#809]
I wanna continue using the stable v0.15. v0.15 is not perfect but it feels more like professional quality software. And I believe v0.15 should be offered side by side the latest version as the stable version. I have used the latest version v0.18 and it is very unstable and not fit for use. Thank you.

And can we not see this notification in the future?

![image](https://user-images.githubusercontent.com/4354982/72676400-c9926800-3a88-11ea-8154-541edc4c89c2.png)

**Comment by vktr** [comment]
Hi! I'm sorry you're not happy with the latest version. I'm a firm believer in rolling forward so any issues that are reported will be fixed in whatever current version we have and will not be backported to previous versions.

Can you give a bit more information on what you mean by 'not fit for use'? It would help me improve PicoTorrent in coming versions :smiley: 

The update available dialog can be ignored for a specific version (if you check the box) but will reappear when a new version is released, sorry.

**Comment by kaecy** [comment]
I strongly believe people should at the other end of stable software. They should not be given alpha software.

And the second point I want to make is...
If somebody is happy using an old version they shouldn't be pushed, forced and shoved until they install the new version. The user should be in control.

**Comment by birkoffe** [comment]
@kaecy 

I feel your pain.
When I know about PicoTorrent in May 2016, there is only one missing feature to me Labes #278. But author start this infinity migration on different frontend (wx, qt). But instead of speeding up the introduction of new features, it has led to a deterioration in the quality of existing functionality.

Rechecking torrent in #407 not fixing 3 year (oh, I'm forgot that with start so long).
Open .torrent files not alwayes handle by PT.
And more, and more...
It's very sad :-(

**Comment by vktr** [comment]
So, I can somewhat understand your opinions and if I had infinite time to pour into the development of PicoTorrent I would do things differently.

Unfortunately, though, this is not my day job, and that means I have to try to make my life as easy as possible when it comes to whatever time I can put into this project. I'm trying different frontends to make my life easier - wxWidgets was easier than WinAPI, but Qt is way easier than wxWidgets, and that's where we are today.

I know there has been issues dragging on for way too long, and I know things are a bit unstable here and there. I'm working on it, and I hope I can wrap everything up in a few more minor releases so I can release a 1.0 later this year.

The harsh truth is, I do this for fun, I have no obligations to support anything for anyone. If you're happy with a version, feel free to keep using it. If you want to maintain that version, feel free to fork it and add/remove whatever features and bugs you like. Everything is open source, which means you have that power.

If you want to help improve PicoTorrent (i.e help me move forward) you are more than welcome to engage in issues, @ me to ask for comments, guidance or whatever you might need. Send pull requests (which you've done @birkoffe and I'm very happy for it!).

Reach out and be constructive. We *are* rolling forward, and *I'm not* maintaining multiple versions.

**Comment by Geograph-us** [comment]
Thanks @kaecy I tried version 0.15 and it works great
Before that I tried the latest version 0.18 and it crashes due to the cyrillic-paths
I think version 0.18 brought back old issues.

P.S. How many years Qt and it still cannot work normally with non-Latin paths in windows?

**Comment by vktr** [comment]
@Geograph-us can you share an example of the issues you’re experiencing with Cyrillic paths?

**Comment by Geograph-us** [comment]
Video example and crashdump
[Desktop 2020.03.23 - 17.18.00.08.mp4.zip](https://github.com/picotorrent/picotorrent/files/4369304/Desktop.2020.03.23.-.17.18.00.08.mp4.zip)
[c0edd019-7a9d-4140-b531-4ae601e49c9c.zip](https://github.com/picotorrent/picotorrent/files/4369309/c0edd019-7a9d-4140-b531-4ae601e49c9c.zip)

**Comment by vktr** [comment]
Thanks @Geograph-us! That really helps!

**Comment by kaecy** [comment]
As long as this post helped one person that's good enough. If you love v0.15 share it.

**Comment by vktr** [comment]
@Geograph-us The issue you mentioned should be fixed in #831
