### ISSUE TITLE
Suggestion: Focus on stability and scaling

### ISSUE THREAD

**Issue by EwolBash** [picotorrent/picotorrent#823]
I do not know if my comments will be welcome, but I hope you will hear me out.

On Windows we do not have reliable clients that scale well like rtorrent. We do have transmission, but it's still considered beta software in Windows and development is primarily focused on the GNU/Linux side of things.

qBittorrent is bleeding edge software with frequent feature additions and frequent updates. There's a lot of people who enjoy qBittorrent and that's fine, that's what freedom of choice is all about. However, it also has major bugs in every version and some of them are quite serious and would be avoidable if more focus was put on stability instead of features.

In picotorrent I see something else a no nonsense client aimed at high performance and stability (if I'm wrong feel free to correct me) I'm just concerned looking through the issues that developers of picotorrent may feel it necessary to play 'catch up' with clients such as qBittorrent and lose sight of what I would like and think is missing from windows clients, performance and stability. There's a reason people still use very old versions of utorrent!

Thank you for the great software.

**Comment by vktr** [comment]
Hi! Thanks for the kind words! I agree that PicoTorrent is aiming to be a stable, high performance BitTorrent client more than a bleeding edge kind of client. I don't think we're playing catch-up as much as we're trying to add (relevant) features requested by users as well as bringing the client up to a modern, stable state. There's been some issues between versions due to switching UI frameworks and such, but I think we're at a point where we're mostly happy with what we got and are trying to stabilize things :)

One of the core reasons for building PicoTorrent was actually that it would be tiny, stable and have high performance and I thank you for the reminder!
