### ISSUE TITLE
IDEA: add torrent irc chat

### ISSUE THREAD

**Issue by ivanjaros** [picotorrent/picotorrent#850]
So I just had this interesting idea that might be worth trying out...

Since you can see your peers that seed/leech the bit torrent file I though that it would be interesting to automatically create a IRC chatroom for that particular torrent file(based on some hash) where you could chat with the fellow clients - directly in the client(so no extra IRC client would be needed). Essentially, each bit torrent file would have a new tab "chat" that once activated, it would open up a simple irc chat in its pane. Nothing fancy, just really simply chat. You could not be present in the room if you do not have the bit torrent file active. That way you would allow only people directly involved with that file to be able to talk. The best part is that there is no need for bot to keep the room open. If there are no people actively seeding/leeching the file, there would be no room to talk in. Once someone is active and opens up the chat tab, the room would create itself, just like standard IRC. No magic needed.

What do you think?

**Comment by mutt3x** [comment]
Where is the weed that you are smoking because i want some of that. Thats what i think.

Private trackers mostly have their own IRC channels where you can talk... for public ones, well better not talk there.
I believe your idea is pure in hearth but in action its just unsafe, bloat and probably feature weak. Torrenting is about content, not chatting with the peer. **I dont see myself chatting with anyone related to seeding something and probably dont want other people to contact me about what im seeding.**

That being said, private trackers might ban the client.
Overall, honestly a bad idea.

**Comment by vktr** [comment]
Hi @ivanjaros! Sorry, I'm on vacation so response time is longer.

I don't think it's something I want in PicoTorrent really. It reminds me a bit of the rating system which could be found in uTorrent back in the day (maybe it's still there, I don't know). I **might** support a plugin API which can help make this happen, but I won't be adding anything like this in the core application, or accept a PR for it. Sorry!
