### ISSUE TITLE
Crash when removing non-metadata torrent and files

### ISSUE THREAD

**Issue by dj245** [picotorrent/picotorrent#855]
If the torrent is in the "Downloading metadata" state, performing the action Remove->Remove torrent and files will cause the program to crash.

I am using Windows 10 with the default settings.

**Comment by vktr** [comment]
Hey @dj245! Thanks for the report! Are you running v0.18?

**Comment by dj245** [comment]
Yes, v0.18.0

**Comment by vktr** [comment]
I think there's an issue reported. And should be fixed in the latest builds (and will be resolved in the next release). You can try them from here, https://ci.appveyor.com/project/picotorrent/picotorrent/build/job/eh8eqjjg4k44mhlm/artifacts.

You might need to uninstall your current version in order to be able to install this one, since it has the same version number.

**Comment by vktr** [comment]
Hi @dj245! Please try the latest version (0.19). Feel free to reopen or create a new issue if it's not resolved.

**Comment by dj245** [comment]
Confirmed resolved thank you.
